name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
      tag:
        description: 'Git Tag to checkout'
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-15
    steps:
      # Проверяем исходный код
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'heiher/hev-socks5-tunnel'
          submodules: true
          path: 'temp'
          ref: ${{ github.event.inputs.tag }}

      # Билдим macOS и iPhoneOS
      - name: Build macOS xcframework
        run: |
          mkdir macos_arm64_x86_64
          mkdir macos_arm64_x86_64/macos_arm64
          mkdir macos_arm64_x86_64/macos_x86_64
          cd temp
          make clean
          make PP=g++ CC=gcc CFLAGS="-arch x86_64 -mmacosx-version-min=12.0" LFLAGS="-arch x86_64 -mmacosx-version-min=12.0" static
          libtool -static -o ../macos_arm64_x86_64/macos_x86_64/libhev-socks5-tunnel.a bin/libhev-socks5-tunnel.a
          make clean

          # Создаём xcframework
          mkdir include
          cp temp/src/hev-main.h include/hev-socks5-tunnel.h
          cp ./Templates/HevSocks5Tunnel.template include/module.modulemap
          xcodebuild -create-xcframework \
                     -library ./iphoneos_arm64/libhev-socks5-tunnel.a \
                     -headers ./include \
                     -library ./iphonesimulator_arm64_x86_64/libhev-socks5-tunnel.a \
                     -headers ./include \
                     -library ./macos_arm64_x86_64/libhev-socks5-tunnel.a \
                     -headers ./include \
                     -output ./HevSocks5Tunnel.xcframework
          zip -r HevSocks5Tunnel.xcframework.zip HevSocks5Tunnel.xcframework

      # Клонируем публичный репозиторий и пушим артефакты
      - name: Push build to public repo
        uses: actions/checkout@v3
        with:
          repository: 'tozik/Tun2SocksKit'
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cp ./HevSocks5Tunnel.xcframework.zip ./tozik/Tun2SocksKit/
          git add .
          git commit -m "Add build: ${{ github.event.inputs.version }}"
          git push
