name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string
      tag:
        description: 'Git Tag to checkout'
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'heiher/hev-socks5-tunnel'
          submodules: 'true'
          path: 'temp'
          ref: ${{ github.event.inputs.tag }}
      - uses: actions/checkout@v3
        with:
          repository: 'tozik/hev-socks5-tunnel-iphonesimulator-new'
          path: 'fake'
          
      - name: build macos arm64_x86_64
        run: |
          mkdir macos_arm64_x86_64
          mkdir macos_arm64_x86_64/macos_arm64
          mkdir macos_arm64_x86_64/macos_x86_64
          cd temp
          make clean
          make PP=g++ \
               CC=gcc \
               CFLAGS="-arch x86_64 -mmacosx-version-min=12.0" \
               LFLAGS="-arch x86_64 -mmacosx-version-min=12.0 -Wl,-Bsymbolic-functions" static
          libtool -static -o ../macos_arm64_x86_64/macos_x86_64/libhev-socks5-tunnel.a \
                  bin/libhev-socks5-tunnel.a \
                  third-part/lwip/bin/liblwip.a \
                  third-part/yaml/bin/libyaml.a \
                  third-part/hev-task-system/bin/libhev-task-system.a
          make clean
          make clean
          make PP=g++ \
               CC=gcc \
               CFLAGS="-arch arm64 -mmacosx-version-min=12.0" \
               LFLAGS="-arch arm64 -mmacosx-version-min=12.0 -Wl,-Bsymbolic-functions" static
          libtool -static -o ../macos_arm64_x86_64/macos_arm64/libhev-socks5-tunnel.a \
                  bin/libhev-socks5-tunnel.a \
                  third-part/lwip/bin/liblwip.a \
                  third-part/yaml/bin/libyaml.a \
                  third-part/hev-task-system/bin/libhev-task-system.a
          cd ../macos_arm64_x86_64
          lipo -create -o ./libhev-socks5-tunnel.a ./macos_arm64/libhev-socks5-tunnel.a ./macos_x86_64/libhev-socks5-tunnel.a

          
      - name: build iphoneos arm64
        run: |
          mkdir iphoneos_arm64
          cd temp
          make clean
          make PP="xcrun --sdk iphoneos --toolchain iphoneos clang" \
               CC="xcrun --sdk iphoneos --toolchain iphoneos clang" \
               CFLAGS="-arch arm64 -mios-version-min=12.0" \
               LFLAGS="-arch arm64 -mios-version-min=12.0 -Wl,-Bsymbolic-functions" static
          libtool -static -o ../iphoneos_arm64/libhev-socks5-tunnel.a \
                  bin/libhev-socks5-tunnel.a \
                  third-part/lwip/bin/liblwip.a \
                  third-part/yaml/bin/libyaml.a \
                  third-part/hev-task-system/bin/libhev-task-system.a
          make clean
          
      - name: build iphonesimulator arm64_x86_64
        run: |
          mkdir iphonesimulator_arm64_x86_64
          mkdir iphonesimulator_arm64_x86_64/iphonesimulator_arm64
          mkdir iphonesimulator_arm64_x86_64/iphonesimulator_x86_64
          cd fake
          make clean
          make PP="xcrun -sdk iphonesimulator clang" \
               CC="xcrun -sdk iphonesimulator clang" \
               CFLAGS="-arch arm64 -mios-simulator-version-min=12.0" \
               LFLAGS="-arch arm64 -mios-simulator-version-min=12.0 -Wl,-Bsymbolic-functions" static
          cp bin/libhev-socks5-tunnel.a ../iphonesimulator_arm64_x86_64/iphonesimulator_arm64/libhev-socks5-tunnel.a
          make clean
          make PP="xcrun -sdk iphonesimulator clang" \
               CC="xcrun -sdk iphonesimulator clang" \
               CFLAGS="-arch x86_64 -mios-simulator-version-min=12.0" \
               LFLAGS="-arch x86_64 -mios-simulator-version-min=12.0 -Wl,-Bsymbolic-functions" static
          cp bin/libhev-socks5-tunnel.a ../iphonesimulator_arm64_x86_64/iphonesimulator_x86_64/libhev-socks5-tunnel.a
          make clean
          cd ../iphonesimulator_arm64_x86_64
          lipo -create -o ./libhev-socks5-tunnel.a ./iphonesimulator_arm64/libhev-socks5-tunnel.a ./iphonesimulator_x86_64/libhev-socks5-tunnel.a
          
      - name: Build xcframework
        run: |
          mkdir include
          cp temp/src/hev-main.h include/hev-socks5-tunnel.h
          cp ./Templates/HevSocks5Tunnel.template include/module.modulemap
          xcodebuild -create-xcframework \
                     -library ./iphoneos_arm64/libhev-socks5-tunnel.a \
                     -headers ./include \
                     -library ./iphonesimulator_arm64_x86_64/libhev-socks5-tunnel.a \
                     -headers ./include \
                     -library ./macos_arm64_x86_64/libhev-socks5-tunnel.a \
                     -headers ./include \
                     -output ./HevSocks5Tunnel.xcframework
          zip -r HevSocks5Tunnel.xcframework.zip HevSocks5Tunnel.xcframework
      
      - name: Update package file
        run: |
          export CHECKSUM=$(shasum -a 256 ./HevSocks5Tunnel.xcframework.zip | awk '{print $1}')
          echo "Computed SHA256 checksum: $CHECKSUM"
          echo "// swift-tools-version: 5.7" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"Tun2SocksKit\"," >> Package.swift
          echo "  platforms: [.iOS(.v15), .macOS(.v15)]," >> Package.swift
          echo "  products: [" >> Package.swift
          echo "    .library(name: \"Tun2SocksKit\", targets: [\"Tun2SocksKit\"])," >> Package.swift
          echo "    .library(name: \"Tun2SocksKitC\", targets: [\"Tun2SocksKitC\"])" >> Package.swift
          echo "  ]," >> Package.swift
          echo "  targets: [" >> Package.swift
          echo "    .target(" >> Package.swift
          echo "      name: \"Tun2SocksKit\"," >> Package.swift
          echo "      dependencies: [\"HevSocks5Tunnel\", \"Tun2SocksKitC\"])" >> Package.swift
          echo "    )," >> Package.swift
          echo "    .target(" >> Package.swift
          echo "      name: \"Tun2SocksKitC\"," >> Package.swift
          echo "      dependencies: \".\"" >> Package.swift
          echo "    )," >> Package.swift
          echo "    .binaryTarget(" >> Package.swift
          echo "      name: \"LibXray\"," >> Package.swift
          echo "      url: \"https://github.com/tozik/Tun2SocksKit/releases/download/${{ github.event.inputs.version }}/LibXray.xcframework.zip\"," >> Package.swift
          echo "      checksum: \"$CHECKSUM\"" >> Package.swift
          echo "    )" >> Package.swift
          echo "  ]" >> Package.swift
          echo ")" >> Package.swift
          
      #- uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
      #    commit_message: Tun2SocksKit Release ${{ github.event.inputs.version }}!!!
      #    commit_user_name: tozik
      #    commit_user_email: tozika@inbox.ru
      #    commit_author: Tozik <tozika@inbox.ru>
      #    tagging_message: ${{ github.event.inputs.version }}
      #    file_pattern: 'Package.swift'
          
      # Проверяем артефакт
      #- name: Zip xcframework
      #  run: |
      #    if [ ! -f HevSocks5Tunnel.xcframework.zip ]; then
      #      echo "Артефакт уже существует, повторная упаковка не требуется."
      #    else
      #      zip -r HevSocks5Tunnel.xcframework.zip ./HevSocks5Tunnel.xcframework
      #    fi
      #    ls -l ./HevSocks5Tunnel.xcframework.zip
      #    shasum -a 256 ./HevSocks5Tunnel.xcframework.zip
                
    #Сохраняем артефакт и Package.swift
      - name: Save artifacts
        run: |
          ls -l ./HevSocks5Tunnel.xcframework.zip
          shasum -a 256 ./HevSocks5Tunnel.xcframework.zip
          mkdir -p /tmp/artifact_backup
          cp HevSocks5Tunnel.xcframework.zip /tmp/artifact_backup/
          cp Package.swift /tmp/artifact_backup/
          
      # Клонируем публичный репозиторий
      - name: Clone public repo
        uses: actions/checkout@v3
        with:
          repository: 'tozik/Tun2SocksKit'
          token: ${{ secrets.SECOND_REPO_TOKEN }}
      
      # Восстанавливаем Package.swift
      - name: Restore Package.swift
        run: |
          cp /tmp/artifact_backup/Package.swift ./
          echo "Содержимое текущего каталога после восстановления Package.swift:"
          ls
      
      # Восстанавливаем и пушим артефакт
      - name: Restore and commit artifact
        run: |
          cp /tmp/artifact_backup/HevSocks5Tunnel.xcframework.zip ./
          echo "Содержимое текущего каталога после восстановления артефакта:"
          ls
          git add Package.swift
          git commit -m "Add build artifact: ${{ github.event.inputs.version }}"
          git push
          ls -l ./HevSocks5Tunnel.xcframework.zip
          shasum -a 256 ./HevSocks5Tunnel.xcframework.zip
      
      # Загрузим релизный артефакт в публичный репозиторий
      - name: Upload release asset to second repo
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          body: 'Release built from source'
          files: ./HevSocks5Tunnel.xcframework.zip
          repository: 'tozik/Tun2SocksKit'
          token: ${{ secrets.SECOND_REPO_TOKEN }}

       # Проверяем checksum после релиза
      - name: Verify checksum in release
        run: |
          curl -LO https://github.com/tozik/Tun2SocksKit/releases/download/${{ github.event.inputs.version }}/HevSocks5Tunnel.xcframework.zip
          export ACTUAL_CHECKSUM=`shasum -a 256 HevSocks5Tunnel.xcframework.zip | awk '{print $1}'`
          echo "Actual checksum: $ACTUAL_CHECKSUM"
          echo "Expected checksum: $(cat /tmp/artifact_backup/Package.swift | grep checksum | awk '{print $2}')"
          if [[ "$ACTUAL_CHECKSUM" != "$(cat /tmp/artifact_backup/Package.swift | grep checksum | awk '{print $2}')" ]]; then
            echo "Checksum mismatch!"
            exit 1
          fi
